### ISSUE TITLE
Expose openAll and closeAll Master-Detail rows

### ISSUE THREAD

**Issue by welsen** [i-Cell-Mobilsoft-Open-Source/icell-data-table#151]
**Describe the solution you'd like**
We would need two API calls exposed to developers, that enables to open-close master/detail views all at once.

**Describe alternatives you've considered**
Without this, we would need to iterate through the rows, and open-close each.

As I remember it still needs to be implemented, but to have this would be great.

**Comment by KissBalazs** [comment]
implemented.
