### ISSUE TITLE
Server side datasource doesn't work with get request

### ISSUE THREAD

**Issue by RudolfDaniel** [i-Cell-Mobilsoft-Open-Source/icell-data-table#38]
**Describe the bug**
Server side datasource doesn't work with get request.

**To Reproduce**
1. Make a get request by server side datasource table.
2. Data table doesn't load the requested data.

**Expected behavior**
Requested data to be loaded into the table.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome

**Comment by mercury83** [comment]
@RudolfDaniel: Server side datasource is designed for server-side paging scenarios (we'll need to update the documentation). A GET request can be good if it sends paging parameters in some way (query params, headers). If the response contains only a list of entities, client-side pagination handling would be more appropriate.
