### ISSUE TITLE
asciidoctor and pandoc tools are required for local build

### ISSUE THREAD

**Issue by KissBalazs** [i-Cell-Mobilsoft-Open-Source/icell-data-table#93]
**Describe the bug**
Running the commands described in the "Examples / Run example project" section requires some third party softwares which are not indicated in the guide.

**To Reproduce**
after install, running `npm run build:prod` will fail with the following message:

```
> @i-cell/data-table@1.0.27-beta.0 docs:readme /home/forest/projects/icell/icell-data-table
> bash ./scripts/readme-adoc2md

./scripts/readme-adoc2md: line 15: -b: command not found
./scripts/readme-adoc2md: line 16: -f: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
```

**Expected behavior**
Should build a local version.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser latest Chrome
 - Version:   1.0.27-beta.0

**Additional context**
Solution: install `asciidoctor` and `pandoc` (on linux):
```
sudo apt-get install asciidoctor
sudo apt-get install pandoc
```

**Comment by welsen** [comment]
The readme convert script already contains install for both.

**Comment by KissBalazs** [comment]
Thanks for the reply, investigating it a bit further I can see now that the problem is with the script:
...
ASCIIDOCTOR_BIN=`command -v asciidoctor`
if ! [ -x $ASCIIDOCTOR_BIN ]; then...
```
After of asking around, I got the solution: if the $ASCIIDOCTOR_BIN command results in an empty string, then the condition will be
`if ! [-x] ` which will always be false. 

I suggest the following fix: we should quote the parameter expansion:
```
if ! [ -x "$ASCIIDOCTOR_BIN" ]; then
...
if ! [ -x "$PANDOC_BIN" ]; then
```

Alternative solution is to use double brackets `[[˙ (in this case parameter expansion works differently)
